### ISSUE TITLE
There are no timeouts for network operations.

### ISSUE THREAD

**Issue by cyisfor** [cryptoscope/netwrap#3]
I think you can set a deadline on net.Conn instances like `conn.SetDeadline(time.Now().add(Duration{100000000}))`. The Go devs in their infinite wisdom make you call "SetDuration" over again every time there is a timeout error which is kind of dumb, but without any sort of timeout, I think every network operation that has a failure on the remote end leaves its goroutine hanging forever waiting for that dead connection to work again.

I noticed this trying out "go-ssb." When I left it running for a while, it accumulated a gigabyte of RAM doing basically nothing, and then when I killed the program, tens of thousands of identical error messages flooded the console, along the lines of `"fetchFeed(%s:%d) gossip pump failed: %w"` in plugins/gossip/handler.go of go-ssb. Then I had to hard kill the program, getting just as many tens of thousands of stack traces from goroutines going belly up in the process. Many of them had been sitting idle for an hour. I think every time "gossip pump" fails, it just hangs the goroutine and leaves all that memory leaking out like a sieve, since there are no timeouts for network operations anywhere I can see.

**Comment by cyisfor** [comment]
Wait, I might be an idiot. There's something in the "gossip" plugin that takes a "context.Context" whose docs say "A Context carries a deadline, a cancellation signal, and other values across API boundaries." So maybe that's where the timeout is being specified, and in that case, I have no idea why goroutines are piling up for me with every failed "gossip pump."

**Comment by cyisfor** [comment]
And now I can't even recreate the conditions where I get tons of goroutines. Meh.

**Comment by cryptix** [comment]
Yup, sorry you had to _trial and error_ through this.

Yea, contexts are supposed to be used for this kind of Timeouts. They are always bound to the connections, and you should be able to cancel them via conn.disconnect as well (ie not just via shutting down the server).

The myriad of calls comes from the fact that EBT is not yet the default but still the old legacy replication which is based on createHistoryStream. I plan to make ebt the default after [this PR](https://github.com/cryptoscope/ssb/pull/111) is merged, tho.
